kind: Deployment
apiVersion: apps/v1
metadata:
  name: mq-dev-server
  namespace: ace-smp-dev
  labels:
    app: mq-dev-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-dev-server
  template:
    metadata:
      labels:
        app: mq-dev-server
    spec:
      containers:
        - name: mq-dev-server
          image: 'ibmcom/mq:latest'
          env:
            - name: LICENSE
              value: accept
            - name: MQ_QMGR_NAME
              value: QM1
            - name: MQ_APP_PASSWORD
              value: passw0rd
          resources:
            requests:
              cpu: 200m
              memory: 700Mi
            limits:
              cpu: 700m
              memory: 1000Mi
          imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
